[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_ENV = "production"

# Enable functions directory
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Basic catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
